/* lang-de.js - German translations */

export const de = {
    // Sidebar Menu
    addSensor: "Sensor hinzufügen",
    searchPlaceholder: "Tippen zum Suchen...",
    clearAll: "Sensorliste löschen",
    addCard: "Card +",
    copyYaml: "YAML für Dashboard kopieren",
    saveView: "Ansicht speichern",
    listEmpty: "Liste leer.",
    layout: "Ansicht (Layout)",
    combined: "Kombiniert",
    split: "Getrennt (Grid)",
    mixed: "Mixed (Beides)",
    showStats: "Statistiken anzeigen",
    donutSidebar: "Donut Sidebar",
    zoomLevel: "Zoom Stufe",
    gridColumns: "Spalten (Grid)",
    lineSmoothing: "Linien-Glättung (0-5)",
    chartType: "Darstellung (Global):",
    line: "Line (Kurve)",
    bar: "Bar (Balken)",
    doughnut: "Donut (Verteilung)",
    stepped: "Stepped (Stufen)",
    scatter: "Scatter (Punkte)",
    stackedArea: "Stacked Area (gestapelt)",
    refLinesSection: "Referenzlinien",
    refLineValue: "Wert",
    refLineAlias: "Bezeichnung",
    addRefLineBtn: "+ REFERENZLINIE HINZUFÜGEN",
    yMinLabel: "Y-Achse Min",
    yMaxLabel: "Y-Achse Max",
    yMinTitle: "Minimalwert Y-Achse. Leer lassen für Auto-Skalierung.",
    yMaxTitle: "Maximalwert Y-Achse. Leer lassen für Auto-Skalierung.",
    autoPlaceholder: "auto",
    autoScale: "Auto-Scale (W ➡ kW)",
    compareYear: "Vorjahresvergleich",
    fillArea: "Fläche füllen",
    hideAxisLabels: "Achsen-Text ausblenden",
    hideGrid: "Gitterlinien ausblenden",
    hideLegend: "Legende ausblenden",
    hideMonoBtn: "Min/Max-Hervorhebungsschaltfläche ausblenden",
    dateFormat: "Datumsformat",
    dateFormatDMY: "Tag.Monat (31.12)",
    dateFormatMDY: "Monat/Tag (12/31)",
    stackedBars: "Stacked Bars",
    timePeriodMode: "Zeitraum Modus:",
    relative: "Relativ",
    calendar: "Kalender",
    resetZoom: "🔍 Zoom zurücksetzen",
    savedViews: "Gespeicherte Ansichten",

    // Time periods
    lastHour: "Letzte 1 Stunde",
    last3Hours: "Letzte 3 Stunden",
    last6Hours: "Letzte 6 Stunden",
    last12Hours: "Letzte 12 Stunden",
    last24Hours: "Letzte 24 Stunden",
    last48Hours: "Letzte 48 Stunden",
    last7Days: "Letzte 7 Tage",
    last30Days: "Letzte 30 Tage (Monat)",
    last3Months: "Letzte 3 Monate",
    lastYear: "Letztes Jahr",
    from: "Von:",
    to: "Bis:",

    // Stat labels
    min: "Min",
    max: "Max",
    avg: "Ø",
    current: "AKTUELL",
    sum: "SUMME",

    // Modal texts
    codeExport: "Code Export",
    yamlHint: "Dieser Code erstellt eine Card (yaml - Kopie für das Dashboard).",
    copy: "Kopieren",
    copySuccess: "Kopieren erfolgreich!",
    jsonHint: 'Hier findest du den JSON-Code für die <b>detailed-charts-views.js</b> Datei. (Siehe Wiki!)',
    customCardImport: "Custom Card Import",
    importHint: "Füge hier den YAML Code deiner Custom Card ein.",
    addCardBtn: "Card hinzufügen",

    // Alerts & errors
    copyFailed: "Kopieren fehlgeschlagen.",
    noSensorsSelected: "Keine Sensoren ausgewählt.",
    sensorAlreadyInList: "Sensor ist bereits in der Liste.",
    addSensorsFirst: "Bitte erst Sensoren hinzufügen.",
    viewNamePrompt: "Name für diese LOKALE Ansicht:",
    deleteViewConfirm: "Ansicht wirklich löschen?",
    globalViewCantDelete: "Globale Ansichten können nur in der JS Datei gelöscht werden.",
    clearAllConfirm: "Alle Sensoren aus der Liste löschen?",
    endDateAfterStart: "Enddatum muss nach Startdatum liegen.",
    scatterOnly24h: "Scatter nur <= 24h.",
    renameSensorPrompt: "Neuer Name für den Sensor:",

    // Tooltips & titles
    moveHandle: "Verschieben",
    showValues: "Werte anzeigen",
    monochromeHighlight: "Min/Max hervorheben (Monochrom)",
    collapseSidebar: "Seitenleiste einklappen",
    openMenu: "Menü öffnen",
    homeAssistantMenu: "Home Assistant Menü",
    selectColor: "Farbe wählen",
    deleteList: "Sensorliste löschen",
    addCustomCard: "Custom Card hinzufügen",
    clickToRename: "Klicken zum Umbenennen: ",
    globalView: "Globale Ansicht (in Datei)",
    delete: "Löschen",
    show: "Einblenden",
    hide: "Ausblenden",
    remove: "Entfernen",
    noViewsSaved: "Keine gespeichert.",
    error: "Fehler",
    criticalError: "Fehler: ",
    loading: "Laden...",

    // Editor specific
    visual: "Visuell",
    yaml: "YAML",
    presentation: "Darstellung",
    timePeriod: "Zeitraum",
    options: "Optionen",
    sensors: "Sensoren",
    chartTypeLabel: "Chart Typ",
    layoutLabel: "Layout",
    zoomLabel: "Zoom",
    columnsLabel: "Spalten",
    refLinesLabel: "Referenzlinien",
    modeLabel: "Modus",
    windowLabel: "Fenster",
    startLabel: "Start",
    endLabel: "Ende",
    fillAreaLabel: "Fläche füllen",
    statisticsLabel: "Statistiken",
    sensorLabel: "Sensor",
    aliasLabel: "Alias",
    aliasPlaceholder: "Anzeigename (leer für Standard)",
    addSensorBtn: "+ SENSOR HINZUFÜGEN",
    rerollColors: "Farben neu würfeln",
    showPeaks: "Peak-Marker (Min/Max/Aktuell)",
    showNowLine: "Jetzt-Linie",
    showDayNight: "Tag/Nacht-Schattierung",
    peakMax: "Max",
    peakMin: "Min",
    peakLast: "Akt.",
    nowLabel: "Jetzt",
    area: "Bereich",
    device: "Gerät",
    addAllInGroup: "Alle Sensoren hinzufügen",
    addSelected: "Auswahl hinzufügen",
};
